# Generated by Django 5.1.5 on 2025-02-14 07:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_pollution', '0019_healthassessment_health_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airqualitydata',
            options={'ordering': ['-received_at']},
        ),
        migrations.RemoveField(
            model_name='airqualitydata',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='airqualitydata',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='airqualitydata',
            name='hum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='airqualitydata',
            name='pre',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='airqualitydata',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airqualitydata',
            name='temp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='airqualitydata',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='aqi',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='co',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='nh3',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='no2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='o3',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='pm10',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='pm25',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='so2',
            field=models.FloatField(null=True),
        ),
    ]
