# Generated by Django 5.0.3 on 2025-03-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_pollution', '0020_alter_airqualitydata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gas_type', models.CharField(max_length=20)),
                ('forecasted_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='air_polluti_date_8c38df_idx'), models.Index(fields=['gas_type'], name='air_polluti_gas_typ_1f3f3b_idx')],
                'unique_together': {('date', 'gas_type')},
            },
        ),
    ]
